project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Machine_Learning_Fundamentals"
            file: content/01_journal/01_Machine_Learning_Fundamentals.qmd
          - text: "02 Supervised_ML_Regression"
            file: content/01_journal/02_Supervised_ML_Regression.qmd
          - text: "03 Automated_Machine_Learning_with_H20_(I)"
            file: content/01_journal/03_Automated_Machine_Learning_with_H20_(I).qmd
          - text: "04 Automated_Machine_Learning_with_H20_(II)"
            file: content/01_journal/04_Automated_Machine_Learning_with_H20_(II).qmd
          - text: "05 Performance_Measures"
            file: content/01_journal/05_Performance_Measures.qmd
          - text: "06 Explaining_Black-Box_Models_With_LIME"
            file: content/01_journal/06_Explaining_Black-Box_Models_With_LIME.qmd
          
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto